"""P3 without the triviality objection: binary-mask training, continuous testing.

The acute concentration sweep (7.13, experiment 1) shows a unimodal curve, but
its peak sits at the training point, inviting "best where trained, so what".
This protocol removes the objection BY CONSTRUCTION:

    training   three BINARY fields (each unit gets exactly 0 or sigma0; the
               graded bumps are binarised on their support).  Pure-corner
               protocol: the net only ever sees the three masks at c = 1.
               Per unit, the trained set of noise levels is {0, sigma0} --
               two points.
    testing    (a) concentration sweep c in [0.05, 4]: every c != 1 is an
               untrained noise level;
               (b) smooth interpolation w between field pairs: the interior
               values w*sigma0 are untrained, and so are the mixed supports.

Whatever smooth structure appears on these axes cannot have been memorised
from the training distribution; it is generated by the crossing physics and
the fixed weights.  The peak LOCATION may still be attributed to training;
the curve SHAPE and the lawful interpolation cannot.

Open-loop capability metrics only (task_err / signal / separation and the
implied mixing coefficient lambda-hat of section 7.11); the closed-loop demo
keeps its own blended-trained network -- see 7.12b for why pure-trained nets
must not be run in the closed loop.

Run from the repository root:
    .venv/bin/python tmp/neuromod_sr_pure.py
"""
from __future__ import annotations

import argparse
import contextlib
import io
import time
from pathlib import Path

import numpy as np
import torch

import sys
sys.path.append(str(Path(__file__).resolve().parents[1]))
sys.path.append(str(Path(__file__).resolve().parent))

from neuromod import fields as F
from neuromod import protocol as P
from neuromod import world

N_HIDDEN = 2
SIGMA0 = 0.8
SEEDS = [7, 11, 23]
CONCENTRATIONS = [0.05, 0.1, 0.2, 0.35, 0.5, 0.7, 0.85, 1.0, 1.2, 1.5, 2.0, 3.0, 4.0]
WS = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
PAIRS = [("food", "threat"), ("threat", "shelter"), ("shelter", "food")]


def make_fields(hidden, device, kind: str):
    """kind="binary": bumps binarised on their support, values in {0, SIGMA0}.
    kind="graded": the original bumps (the standard benchmark fields).
    The SUPPORT is identical in both (binarisation acts after the theta-cut),
    so the overlap structure -- the thing that must not change -- is shared."""
    graded = F.build_fields(world.CATEGORIES, hidden, SIGMA0, 0.22, 0.15)
    if kind == "graded":
        return {k: v.to(device) for k, v in graded.items()}
    return {k: (SIGMA0 * (v > 0).float()).to(device) for k, v in graded.items()}


def implied_lambda(y, ta, tb):
    """Least-squares mixing coefficient: y ~ (1-l)*ta + l*tb  (section 7.11)."""
    d = (tb - ta).flatten()
    return float(((y - ta).flatten() @ d) / (d @ d))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--epochs", type=int, default=4000,
                   help="Pure-corner training epochs (full batch) [4000]")
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--hidden-dim", type=int, default=144)
    p.add_argument("--samples", type=int, default=64)
    p.add_argument("--crossing-h", type=float, default=0.2)
    p.add_argument("--grid-side", type=int, default=61)
    p.add_argument("--fields", choices=("binary", "graded"), default="binary")
    p.add_argument("--out-dir", default="tmp/out/sr_standard")
    args = p.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    objects = world.make_scripted_objects()
    alphas = world.alpha_states(None)
    positions = world.make_training_grid(args.grid_side)
    obs = torch.tensor(world.encode_observations(positions, objects),
                       dtype=torch.float32, device=device)
    targets = {s: torch.tensor(world.make_behavior_targets(
                   positions, objects, alphas[s]),
                   dtype=torch.float32, device=device) for s in world.STATES}
    nf = make_fields(args.hidden_dim, device, args.fields)
    state_fields = {s: nf[world.STATE_TO_FIELD[s]] for s in world.STATES}
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    for seed in SEEDS:
        t0 = time.time()
        torch.manual_seed(seed)
        np.random.seed(seed)
        net = P.build_network(args.hidden_dim, n_hidden=N_HIDDEN, base_std=SIGMA0,
                              kind="sample", t=args.samples,
                              crossing_h=args.crossing_h,
                              in_dim=world.obs_dim()).to(device)
        with contextlib.redirect_stdout(io.StringIO()):
            P.train(net, obs, targets, state_fields, world.STATES, N_HIDDEN,
                    args.epochs, args.lr, chunk=1024)
        net.eval()
        final = P.final_losses(net, obs, targets, state_fields, world.STATES,
                               N_HIDDEN)
        print(f"[seed {seed}] pure-binary trained ({time.time()-t0:.0f}s)  "
              + "  ".join(f"{k.split('_')[0]}={v:.4f}" for k, v in final.items()))

        # (a) concentration sweep on the binary corners
        rows = []
        for c in CONCENTRATIONS:
            scaled = {k: v * c for k, v in nf.items()}
            sep, sig, err = P.capability(net, obs, targets, scaled,
                                         world.CATEGORIES, world.STATES,
                                         world.STATE_TO_FIELD, N_HIDDEN)
            rows.append([c, sep, sig, err])
            print(f"  c={c:5.2f}  signal={sig:.3f} sep={sep:.3f} err={err:.3f}")
        with open(out / f"pure_{args.fields}_conc_seed{seed}.csv" if args.fields != "binary" else out / f"pure_conc_seed{seed}.csv", "w") as f:
            f.write("# pure-binary training; concentration sweep (untrained for c!=1)\n")
            f.write(f"# seed={seed} sigma0={SIGMA0} h={args.crossing_h} "
                    f"epochs={args.epochs}\n")
            f.write("# columns: c,separation,signal,task_err\n")
            for r in rows:
                f.write(",".join(f"{v:.6g}" for v in r) + "\n")

        # (b) smooth interpolation between binary corners (untrained interior)
        rows = []
        with torch.no_grad():
            for a, b in PAIRS:
                sa = [s for s, ff in world.STATE_TO_FIELD.items() if ff == a][0]
                sb = [s for s, ff in world.STATE_TO_FIELD.items() if ff == b][0]
                ta, tb = targets[sa], targets[sb]
                for w in WS:
                    fw = (1 - w) * nf[a] + w * nf[b]
                    y = P.evaluate_vector_field(net, obs, fw, N_HIDDEN)
                    lam = implied_lambda(y, ta, tb)
                    err_mix = float(((y - ((1 - w) * ta + w * tb)) ** 2).mean())
                    rows.append([PAIRS.index((a, b)), w, lam, err_mix])
        with open(out / f"pure_{args.fields}_interp_seed{seed}.csv" if args.fields != "binary" else out / f"pure_interp_seed{seed}.csv", "w") as f:
            f.write("# pure-binary training; interpolation sweep "
                    "(interior fields untrained)\n")
            f.write("# pair codes: 0=food-threat 1=threat-shelter 2=shelter-food\n")
            f.write("# columns: pair,w,implied_lambda,err_vs_mixed_target\n")
            for r in rows:
                f.write(",".join(f"{v:.6g}" for v in r) + "\n")
        print(f"  interpolation sweep saved "
              f"(lambda-hat monotone check: see CSV)")


if __name__ == "__main__":
    main()
